name: CICD pipeline

on:
  push:
    branches: [main]

jobs:
  deploy_code:
    name: deploy_code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm run install-all

      # Optional build step
      # - name: Build client
      #   run: npm run build

      - name: Deploy to AWS
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ec2-52-71-253-131.compute-1.amazonaws.com
          REMOTE_USER: ubuntu
          TARGET: "/var/www/cps/"
          EXCLUDE: |
            node_modules
            .next
            .git
            .github
            dist
            build

      # - name: Restart server
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ec2-52-71-253-131.compute-1.amazonaws.com
      #     username: ubuntu
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd /var/www/cps/backend
      #       npm run restart
